GENERATOR: Visual Studio 17 2022
ARCH: x64
TOOLSET: v143

GIT: https://github.com/google/googletest.git
BRANCH: main
FORCE_UPDATE:
CMAKE_CONFIG: -DBUILD_GMOCK=OFF -DBUILD_GTEST=ON -DBUILD_SHARED_LIBS=ON -Dgtest_force_shared_crt=ON -DGTEST_CREATE_SHARED_LIBRARY=1
BUILD_CONFIG:
BUILD_TYPE:

# GIT: https://gitlab.com/libeigen/eigen.git
# BRANCH:
# FORCE_UPDATE:
# CMAKE_CONFIG:
# BUILD_CONFIG:
# BUILD_TYPE:

GIT: https://github.com/alandefreitas/matplotplusplus.git
BRANCH:
FORCE_UPDATE:
CMAKE_CONFIG: -DCMAKE_BUILD_TYPE=Release -DCMAKE_CXX_FLAGS="/O2" -DMATPLOTPP_BUILD_EXAMPLES=ON -DMATPLOTPP_BUILD_TESTS=ON
BUILD_CONFIG:
BUILD_TYPE:


# GIT: https://github.com/opencv/opencv.git
# BRANCH:
# FORCE_UPDATE:
# CMAKE_CONFIG: -DBUILD_PERF_TESTS=OFF -DBUILD_TESTS=OFF -DBUILD_DOCS=OFF  -DWITH_CUDA=OFF -DBUILD_EXAMPLES=OFF -DINSTALL_CREATE_DISTRIB=ON
# BUILD_CONFIG:
# BUILD_TYPE: debug


# GIT: https://github.com/mherb/kalman.git
# BRANCH:
# FORCE_UPDATE:
# CMAKE_CONFIG: -DEigen3_INCLUDE_DIR:"C:\repos\eigen\build\install\include" -DBUILD_TESTING=OFF
# BUILD_CONFIG:
# BUILD_TYPE:


# GIT: https://github.com/nlohmann/json.git
# BRANCH:
# FORCE_UPDATE:
# CMAKE_CONFIG:
# BUILD_CONFIG:
# BUILD_TYPE:

# GIT: https://github.com/jbeder/yaml-cpp.git
# BRANCH:
# FORCE_UPDATE:
# CMAKE_CONFIG:
# BUILD_CONFIG:
# BUILD_TYPE: